# .github/workflows/build.yml

name: Build Electron Application (Windows only)

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 1. Check out git repository
        uses: actions/checkout@v4

      - name: 2. Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 3. Install dependencies
        run: npm ci

      - name: 4. Build/make application
        run: npm run make

      - name: 5. Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: studystack-windows
          path: out/make
